openapi: 3.0.0
info:
  title: Todo Fastify service
  version: 1.0.0
servers:
  - url: localhost:3000
paths:
  /api/todo/:
    get:
      tags:
        - default
      summary: Get Todos
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Add Todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                done:
                  type: boolean
              required:
                - description
              example:
                description: Start code review
                done: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/todo/1:
    put:
      tags:
        - default
      summary: Update Todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                description:
                  type: string
                done:
                  type: boolean
              required:
                - description
                - id
              example:
                title: Complete generic code review
                done: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Todo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get Todo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
